import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coffee limiter",
  description:
    "Generated by William Baele to help you to manage your coffee consumption. Set a target and don't exceed it.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={raleway.className}>{children}</body>
        <Analytics />
        <SpeedInsights />
      </html>
    </>
  );
}
